branches:
  except:
    - gh-pages
language: perl
sudo: false
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
#before_install:
#  - cpanm --notest Devel::Cover::Report::Coveralls
#  - cpanm --notest Test::Code::TidyAll 
#  - cpanm --notest Test::Perl::Critic
#  - cpanm --notest Test::Version
#after_success:
#  - cover -test -report coveralls
